# Generated by Django 5.1.3 on 2024-12-01 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("loan_name", models.CharField(max_length=255)),
                (
                    "principal_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                ("interest_rate", models.DecimalField(decimal_places=2, max_digits=5)),
                ("tenure_months", models.PositiveIntegerField()),
                (
                    "monthly_installment",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "remaining_balance",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("A", "Active"), ("P", "Paid")],
                        default="A",
                        max_length=1,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
        ),
    ]
