# Generated by Django 5.1.3 on 2024-12-01 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="is_payment",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loan_payments",
                to="loan.loan",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=15, null=True
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_payment_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
