# Generated by Django 5.1.3 on 2024-12-01 07:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0002_expensecategory_expense"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="due_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
